import Link from "next/link";
import { Badge, LinkTabs, PageHeader, Panel, Signed } from "@/components/ui";
import type { SegmentStats } from "@/lib/demo/analytics";
import { REPORT_BASELINE_WEEKS, REPORT_MARKET_WEEKS, REPORT_MIN_MARKET_N, reportHeadline, reportWeeks, weeklyReport, type Severity } from "@/lib/demo/report";
import { fmtDate, fmtInt, fmtPct, fmtPp, fmtSignedPct } from "@/lib/format";
import { terminal } from "@/lib/terminal";

export const metadata = { title: "Weekly Model Report · ODDSIQ" };

const TONE: Record<Severity, "neutral" | "warning" | "critical"> = { info: "neutral", watch: "warning", issue: "critical" };
const LABEL: Record<Severity, string> = { info: "Note", watch: "Watch", issue: "Potential issue" };
const th = "px-2.5 py-2 font-medium";

export default async function ReportPage({ searchParams }: { searchParams: Promise<{ week?: string }> }) {
  const t = await terminal();
  const { week: weekParam } = await searchParams;
  const rows = t.ledgerRows();
  const weeks = reportWeeks(rows);
  const week = weeks.find((w) => new Date(w).toISOString().slice(0, 10) === weekParam) ?? weeks[0];
  if (week === undefined)
    return (
      <div className="space-y-4">
        <PageHeader title="Weekly Model Report" subtitle="A weekly summary of how the ledgered predictions scored." />
        <Panel title="No settled weeks yet">
          <p className="px-4 py-3 text-sm text-muted">The report starts once the first ledger predictions have settled. Real-model predictions are recorded in the 24 hours before kickoff and settle from the result.</p>
        </Panel>
      </div>
    );
  const r = weeklyReport(rows, week, t.marketRows());
  const versions = r.week.versions.join(", ") || "—";

  const compare = (label: string, a: number, b: number, fmt: (x: number) => string, lowerIsBetter = false) => (
    <tr className="border-b border-line/60">
      <td className="px-2.5 py-2 pl-4">{label}</td>
      <td className="num px-2.5 py-2 text-right">{fmt(a)}</td>
      <td className="num px-2.5 py-2 text-right text-ink-2">{fmt(b)}</td>
      <td className="num px-2.5 py-2 pr-4 text-right">
        <Signed value={lowerIsBetter ? b - a : a - b}>{Number.isFinite(a - b) ? `${a - b >= 0 ? "+" : "−"}${fmt(Math.abs(a - b)).replace(/^[+−]/, "")}` : "—"}</Signed>
      </td>
    </tr>
  );

  const segTable = (title: string, list: SegmentStats[]) => (
    <Panel title={title} right={`Last ${REPORT_MARKET_WEEKS} weeks · n ≥ ${REPORT_MIN_MARKET_N}`}>
      {list.length === 0 ? (
        <p className="px-4 py-4 text-sm text-muted">No league or market has enough settled predictions.</p>
      ) : (
        <table className="w-full text-[12.5px]">
          <thead>
            <tr className="border-b border-line text-[10.5px] uppercase tracking-wider text-muted">
              <th className={`${th} pl-4 text-left`}>Segment</th>
              <th className={`${th} text-right`}>n</th>
              <th className={`${th} text-right`}>Model / market Brier</th>
              <th className={`${th} pr-4 text-right`}>Avg CLV</th>
            </tr>
          </thead>
          <tbody>
            {list.map((s) => (
              <tr key={s.key} className="border-b border-line/60">
                <td className="px-2.5 py-2 pl-4">{s.label}</td>
                <td className="num px-2.5 py-2 text-right">{fmtInt(s.n)}</td>
                <td className="num px-2.5 py-2 text-right">
                  <Signed value={s.marketBrier - s.brier}>{s.brier.toFixed(3)}</Signed> <span className="text-muted">/ {s.marketBrier.toFixed(3)}</span>
                </td>
                <td className="num px-2.5 py-2 pr-4 text-right">
                  <Signed value={s.avgClv}>{fmtSignedPct(s.avgClv)}</Signed>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </Panel>
  );

  return (
    <div className="space-y-4">
      <PageHeader
        title="Weekly Model Report"
        subtitle={`Predictions recorded in the week of ${fmtDate(r.weekStart)} – ${fmtDate(r.weekEnd - 1)}, compared with the previous ${REPORT_BASELINE_WEEKS} weeks. Generated by fixed rules from the prediction ledger.`}
        right={<Badge tone={t.live ? "neutral" : "warning"}>{t.live ? "Historical · live ledger" : "Historical · DEMO DATA"}</Badge>}
      />
      <LinkTabs label="Week" active={new Date(week).toISOString().slice(0, 10)} items={weeks.map((w) => ({ id: new Date(w).toISOString().slice(0, 10), label: `w/c ${fmtDate(w)}`, href: `/model-lab/report?week=${new Date(w).toISOString().slice(0, 10)}` }))} />

      <Panel title="Summary">
        <p className="px-4 pt-3 text-[15px] leading-relaxed">{reportHeadline(r)}</p>
        <ul className="space-y-2 px-4 py-3">
          {r.findings.map((f, i) => (
            <li key={i} className="flex gap-3 text-[13px] leading-relaxed">
              <span className="w-32 shrink-0">
                <Badge tone={TONE[f.severity]}>{LABEL[f.severity]}</Badge>
              </span>
              <span>
                <span className="text-muted">{f.area}: </span>
                {f.text}
              </span>
            </li>
          ))}
        </ul>
        <p className="border-t border-line px-4 py-2 text-[11px] text-muted">
          n = {fmtInt(r.week.n)} settled ({fmtInt(r.pending)} still pending) · models {versions} · source: ODDSIQ prediction ledger. Findings say &ldquo;potential issue detected&rdquo; when a check crosses its threshold; none is a verdict that the model is broken.
        </p>
      </Panel>

      <div className="grid gap-4 xl:grid-cols-2">
        <Panel title="Performance, market accuracy and calibration" right={`This week vs previous ${REPORT_BASELINE_WEEKS} weeks`}>
          <table className="w-full text-[12.5px]">
            <thead>
              <tr className="border-b border-line text-[10.5px] uppercase tracking-wider text-muted">
                <th className={`${th} pl-4 text-left`}>Metric</th>
                <th className={`${th} text-right`}>Week (n {fmtInt(r.week.n)})</th>
                <th className={`${th} text-right`}>Baseline (n {fmtInt(r.baseline.n)})</th>
                <th className={`${th} pr-4 text-right`}>Change</th>
              </tr>
            </thead>
            <tbody>
              {compare("Hit rate", r.week.hitRate, r.baseline.hitRate, (x) => fmtPct(x))}
              {compare("Mean predicted", r.week.meanPredicted, r.baseline.meanPredicted, (x) => fmtPct(x))}
              {compare("Brier score (model)", r.week.brier, r.baseline.brier, (x) => x.toFixed(4), true)}
              {compare("Brier score (closing market)", r.week.marketBrier, r.baseline.marketBrier, (x) => x.toFixed(4), true)}
              {compare("Log loss", r.week.logLoss, r.baseline.logLoss, (x) => x.toFixed(4), true)}
              {compare("Observed − predicted win rate", r.week.biasPp / 100, r.baseline.biasPp / 100, (x) => fmtSignedPct(x))}
              {compare("Average CLV", r.week.avgClv, r.baseline.avgClv, (x) => fmtSignedPct(x))}
              {compare("Positive CLV share", r.week.positiveClvShare, r.baseline.positiveClvShare, (x) => fmtPct(x))}
            </tbody>
          </table>
          <p className="border-t border-line px-4 py-2 text-[11px] text-muted">
            Accuracy vs market z = {Number.isFinite(r.skillZ) ? r.skillZ.toFixed(2) : "—"} (positive = model lost ground on the close) · CLV z = {Number.isFinite(r.clvZ) ? r.clvZ.toFixed(2) : "—"}. Historical; past results do not predict future ones.
          </p>
        </Panel>

        <Panel title="Largest errors this week" right="Known facts, then possible explanations">
          <ul className="divide-y divide-line">
            {r.misses.map((m) => (
              <li key={m.row.prediction.id} className="px-4 py-2.5 text-[13px]">
                <div>
                  {m.row.event.homeName} vs {m.row.event.awayName} · {m.row.marketName}: {m.row.selectionName}
                </div>
                <div className="num text-xs text-ink-2">
                  Model {fmtPct(m.row.prediction.probability)} · closing market {fmtPct(m.row.closingFairProbability)} · result {m.row.result} {m.row.event.score ? `(${m.row.event.score.home}–${m.row.event.score.away})` : ""} · error {fmtPp(m.errorPp)}
                </div>
              </li>
            ))}
          </ul>
          <p className="border-t border-line px-4 py-2 text-[11px] text-muted">
            Possible explanations, not verified: normal variance, late lineup or injury information, a red card, or model overconfidence. One result says little about a model; see <Link href="/model-lab/errors" className="text-accent hover:underline">Error Analysis</Link> for patterns tested on large samples.
          </p>
        </Panel>

        {segTable("Strongest segments", r.markets.strongest)}
        {segTable("Weakest segments", r.markets.weakest)}

        <Panel title="Model drift" right={<Badge tone={r.drift.status === "STABLE" ? "good" : r.drift.status === "WATCH" ? "warning" : "critical"}>{r.drift.status}</Badge>}>
          <ul className="divide-y divide-line text-[13px]">
            {r.drift.checks.map((c) => (
              <li key={c.id} className="flex justify-between px-4 py-2">
                <span>{c.label}</span>
                <span className="num text-ink-2">
                  {c.statisticLabel} {Number.isFinite(c.statistic) ? c.statistic.toFixed(2) : "—"} · {c.status}
                </span>
              </li>
            ))}
          </ul>
          <p className="border-t border-line px-4 py-2 text-[11px] text-muted">
            Last 28 days vs the 84 before, as of the end of this week. Details on the <Link href="/model-lab/drift" className="text-accent hover:underline">Drift Monitor</Link>.
          </p>
        </Panel>

        <Panel title="Data quality" right="Open markets now">
          <dl className="grid grid-cols-2 gap-x-4 gap-y-2 px-4 py-3 text-sm">
            <dt className="text-muted">Average data quality</dt>
            <dd className="num text-right">{Number.isFinite(r.dataQuality.avgScore) ? r.dataQuality.avgScore.toFixed(0) : "—"} / 100</dd>
            <dt className="text-muted">Bookmakers quoting</dt>
            <dd className="num text-right">{fmtPct(r.dataQuality.completeness, 0)}</dd>
            <dt className="text-muted">Stale or missing odds</dt>
            <dd className="num text-right">
              {fmtInt(r.dataQuality.staleOdds)} of {fmtInt(r.dataQuality.markets)}
            </dd>
          </dl>
          <p className="border-t border-line px-4 py-2 text-[11px] text-muted">Live snapshot at the time of reading, not a weekly figure. {t.dataLabel}.</p>
        </Panel>
      </div>

      <Panel title="Recommended areas for investigation">
        <ol className="list-decimal space-y-1.5 py-3 pr-4 pl-9 text-[13px]">
          {r.findings.filter((f) => f.severity !== "info").length === 0 ? (
            <li>Nothing crossed a threshold this week. Keep monitoring the drift checks and the weakest segments.</li>
          ) : (
            r.findings.filter((f) => f.severity !== "info").map((f, i) => <li key={i}>{f.area}: {f.text}</li>)
          )}
        </ol>
      </Panel>
    </div>
  );
}
