// Market commentary (spec §22) and the "What changed?" summary (§35).
// Every sentence is a template filled only with supplied data: prices,
// bookmaker counts, model outputs, model attributions and news items.
// Timing is reported as timing; causes are never asserted.

import { fmtOdds, fmtPct, fmtPp, fmtSignedPct, fmtTime } from "@/lib/format";
import type { MarketDetail } from "./store";

export const COMMENTARY_NOTE = "Generated by fixed templates from the data on this page. It uses no information beyond what is shown, reports timing rather than causes, and is not a recommendation.";

const HOUR = 3_600_000;

function priceAt(d: MarketDetail, at: number): number | undefined {
  let best: MarketDetail["chart"][number] | undefined;
  for (const p of d.chart) if (!best || Math.abs(p.at - at) < Math.abs(best.at - at)) best = p;
  return best?.consensus;
}

export function marketCommentary(d: MarketDetail, now: number): string[] {
  const { row, analysis, event } = d;
  const name = row.selection;
  const end = Math.min(now, event.kickoff);
  const current = d.chart.at(-1)?.consensus ?? row.currentOdds;
  const sixAgo = priceAt(d, end - 6 * HOUR);
  const out: string[] = [];

  if (sixAgo !== undefined && Math.abs(current / sixAgo - 1) >= 0.01) {
    out.push(
      `The ${name} price has ${current < sixAgo ? "shortened" : "drifted"} from ${fmtOdds(sixAgo)} to ${fmtOdds(current)} during the last six hours${event.status === "scheduled" ? "" : " before kickoff"}. Since opening, ${row.booksMovedSinceOpen} of ${row.booksQuoting} quoting bookmakers have moved more than 1% in the consensus direction.`,
    );
  } else {
    out.push(`The ${name} consensus price is ${fmtOdds(current)}, little changed over the last six hours (opened at ${fmtOdds(d.chart[0]?.consensus)}).`);
  }

  const model = analysis.ensemble.probability;
  const market = d.siblings.find((s) => s.selectionId === row.selectionId)?.marketProbability ?? row.marketProbability;
  const diff = (model - market) * 100;
  out.push(
    `${event.status === "scheduled" ? "The ODDSIQ ensemble currently estimates" : "At kickoff the ODDSIQ ensemble estimated"} ${fmtPct(model)} (uncertainty range ${fmtPct(analysis.ensemble.ciLow, 0)}–${fmtPct(analysis.ensemble.ciHigh, 0)}), compared with an implied market probability of ${fmtPct(market)}. The model therefore ${event.status === "scheduled" ? "shows" : "showed"} a ${fmtPp(diff)} difference.`,
  );

  const drivers = [...analysis.factors].sort((a, b) => Math.abs(b.contributionPp) - Math.abs(a.contributionPp)).slice(0, 2);
  if (drivers.length) out.push(`The largest model attributions are ${drivers.map((f) => `${f.label} (${f.value}, ${fmtPp(f.contributionPp)})`).join(" and ")}. Attributions describe the model, not the match.`);

  const spread = row.modelStdevPp;
  if (spread !== null && row.modelDisagreement) out.push(`Component models spread ${spread.toFixed(1)} pp around the ensemble; disagreement is ${row.modelDisagreement.toLowerCase()}, and confidence is ${row.confidence ?? "—"} of 100.`);

  const lineups = event.lineupConfirmedAt !== undefined && event.lineupConfirmedAt <= now;
  const lastNews = d.news.at(-1);
  out.push(`${lineups ? `Lineups were confirmed at ${fmtTime(event.lineupConfirmedAt!)} UTC.` : "Lineups have not yet been confirmed."}${lastNews ? ` Latest news item (${fmtTime(lastNews.at)} UTC): “${lastNews.text}”.` : ""}`);
  return out;
}

/** One-paragraph summary of the sequence in the "What changed?" timeline. */
export function whatChangedSummary(d: MarketDetail): string {
  const open = d.chart[0]?.consensus;
  const last = d.chart.at(-1)?.consensus;
  if (open === undefined || last === undefined) return "No price history yet.";
  const parts = [`Since opening at ${fmtOdds(open)} the consensus price has moved to ${fmtOdds(last)} (${fmtSignedPct(last / open - 1)}).`];
  let biggest: { text: string; at: number; move: number } | null = null;
  for (const n of d.news) {
    const before = priceAt(d, n.at - 5 * 60_000);
    const after = priceAt(d, n.at + 30 * 60_000);
    if (before === undefined || after === undefined) continue;
    const move = after / before - 1;
    if (!biggest || Math.abs(move) > Math.abs(biggest.move)) biggest = { text: n.text, at: n.at, move };
  }
  if (biggest && Math.abs(biggest.move) >= 0.01) parts.push(`The largest change around a news item was ${fmtSignedPct(biggest.move)} in the 30 minutes after “${biggest.text}” (${fmtTime(biggest.at)} UTC). The data shows the timing only, not whether the news moved the price.`);
  else if (d.news.length) parts.push(`${d.news.length} news item${d.news.length === 1 ? "" : "s"} arrived; none was followed by a price change of 1% or more within 30 minutes.`);
  else parts.push("No news items were recorded for this match.");
  return parts.join(" ");
}
